### ISSUE TITLE
Feature: Sticky piston block pushing

### ISSUE THREAD

**Issue by DeathToCountry** [MineDragonCZ/JSGMod#169]
**Is your feature request related to a problem? Please describe.**
Trying to make it so the gate comes up out of the ground, rendered and non rendered gate blocks don't move based on sticky piston power

**Describe the solution you'd like**
Both rendered and non rendered gates to be able to be moved via sticky pistons

**Describe alternatives you've considered**
Tried OpenComputers' Drone with Piston Upgrade to move blocks with no success

**Comment by MineDragonCZ** [comment]
Not possible in mc 1.12.2 due to how tile entities works
