### ISSUE TITLE
Bug: Can't craft some crystals

### ISSUE THREAD

**Issue by Kevlaris** [MineDragonCZ/JSGMod#170]
I tried to craft some crystals when building a new Stargate, and it just didn't work. I checked the recipe in JEI and it wasn't working there either. However, I could still craft the Teleportation Crystal just fine for some reason. (Light, Ender and Power can't be crafted)

Might be worth noting that I had actually crafted all of these crystals before **in the same session** without any problems. I was playing with a friend through a Hamachi server at the time and he couldn't craft them either. When I loaded in a singleplayer world, it still wasn't working. I have no idea what caused it and how it might be recreated. (I'll check later again if it decides to work for some reason)
**Mod version**: `aunis-1.12.2-4.10.1.0-client`

![image](https://user-images.githubusercontent.com/64031412/177210607-7d321203-f54c-415e-984c-b680f56d6051.png)
![image](https://user-images.githubusercontent.com/64031412/177210613-73a7f0c7-e7b7-4706-b831-5da5410b0e64.png)
![image](https://user-images.githubusercontent.com/64031412/177210620-99686dab-4f9b-4bf3-ae59-446703730431.png)
![image](https://user-images.githubusercontent.com/64031412/177210630-de306041-7cd6-4df5-9a1f-e27faf70b8f4.png)

**Comment by MineDragonCZ** [comment]
Already fixed in dev version of the mod :) But thanks for reporting that bug :)
