### ISSUE TITLE
Bug: cashing another mod

### ISSUE THREAD

**Issue by JPr874** [MineDragonCZ/JSGMod#179]
I have "the dalek mod" on, with JSG mod.
https://swdteam.com/p/dalek-mod
but its my game to crash on load up.
however when i take JSG off the game doesnt crash.
i am using JSG 4.10.1.0

i would like to have both mods on

![Screenshot (1)](https://user-images.githubusercontent.com/81537991/182017691-bd61ab7d-a3d7-4caf-95a4-c647dfbd7e49.png)

**Comment by Fredyman95** [comment]
Thats helpful as hell... crash code -1 can cause hundreds of things. You MUST SEND CRASH REPORT!!!!!!!!

**Comment by JPr874** [comment]
[crash-2022-07-31_18.25.38-client.txt](https://github.com/MineDragonCZ/JSGMod/files/9228508/crash-2022-07-31_18.25.38-client.txt)

**Comment by Fredyman95** [comment]
Alocate more RAM thats all

**Comment by JPr874** [comment]
ok
