### ISSUE TITLE
Bug: Notebook Page recipe is shaped instead of shapeless

### ISSUE THREAD

**Issue by TinyDeskEngineer06** [MineDragonCZ/JSGMod#181]
Fairly self explanatory. The recipe for the Notebook Page is set as a shaped recipe instead of a shapeless recipe.

Version: 1.12.2-4.10.1.0

**Comment by MR-Spagetty** [comment]
https://github.com/MineDragonCZ/JSGMod/pull/104

**Comment by TinyDeskEngineer06** [comment]
Oh.
