### ISSUE TITLE
Bug: Repeated deaths by entering "wrong side" of gate

### ISSUE THREAD

**Issue by TinyDeskEngineer06** [MineDragonCZ/JSGMod#182]
Bug Description:
I have a dedicated multiplayer survival server running JSG and I have a stargate built at spawn. For a few minutes everything worked as intended, but suddenly when I dialed into another gate, I died after going through the gate, the death message being the one for entering the exit gate. However, the gate I entered was the one I was dialing from. I tried again and again, but every time it killed me. However, immediately after temporarily going into Creative so I could get to the other side and dying to the gate once more in Survival, it started working as expected again.

1: Create and join server
2: Enter Survival
3: Dial a gate repeatedly until bug occurs

Expected Behavior:
The gate should not kill a player if they enter from the correct side and the receiving gate does not have its iris closed.

Mod Version: 1.12.2-4.10.1.0

**Comment by Fredyman95** [comment]
Known bug #163 . Next time check reproted bugs/issues, please
