### ISSUE TITLE
JSG WIKI Issue:

### ISSUE THREAD

**Issue by lukasz4444** [MineDragonCZ/JSGMod#183]
@MR-Spagetty 

https://justsgmod.eu/servers/jsgcraft/#Banned%20players

I'm not asking to be removed from the block list, but I am requesting that my account **be removed from that website immediately.**
And this is it

**Comment by MR-Spagetty** [comment]
Firstly that is not the wiki and i have no control over that bit and secondly this is not the place to talk about pretty much anything pertaining to the website

**Comment by lukasz4444** [comment]
ok. so who can do this ?

**Comment by lukasz4444** [comment]
> Firstly that is not the wiki and i have no control over that bit and secondly this is not the place to talk about pretty much anything pertaining to the website

okay but i have no other way to ask for this so i use github.
